module.exports = {
  ROLES: {
    CUSTOMER: 'CUSTOMER',
    EMPLOYEE: 'EMPLOYEE',
    ADMIN: 'ADMIN',
  },
  ACCOUNT_STATUS: {
    ACTIVE: 'ACTIVE',
    FROZEN: 'FROZEN',
  },
  TRANSACTION_TYPE: {
    DEPOSIT: 'DEPOSIT',
    WITHDRAWAL: 'WITHDRAWAL',
    TRANSFER: 'TRANSFER',
    PAYMENT: 'PAYMENT',
  },
  TRANSACTION_STATUS: {
    PENDING: 'PENDING',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
    REJECTED: 'REJECTED',
  },
  ALERT_STATUS: {
    OPEN: 'OPEN',
    UNDER_REVIEW: 'UNDER_REVIEW',
    CLEARED: 'CLEARED',
    CONFIRMED_SUSPICIOUS: 'CONFIRMED_SUSPICIOUS',
  },
  ALERT_SEVERITY: {
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH',
    CRITICAL: 'CRITICAL',
  },
  RULE_TYPE: {
    LARGE_TRANSACTION: 'LARGE_TRANSACTION',
    HIGH_FREQUENCY: 'HIGH_FREQUENCY',
    STRUCTURING: 'STRUCTURING',
  },
  RISK_LEVEL: {
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH',
    CRITICAL: 'CRITICAL',
  },
  CURRENCY: {
    INR: 'INR',
  },
};
